# -*- coding: utf-8 -*-
"""Untitled34.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19MuZ5a1sLhuGIwQ9S0xCwS9uCpvx222a
"""

import streamlit as st
from PIL import Image

st.title("Monitoria da vegetação")

# Create a file uploader widget
uploaded_files = st.file_uploader("Choose Sentinel-2 images:", type="tif", multiple=True)

if uploaded_files is not None:
    # Display the uploaded images
    for uploaded_file in uploaded_files:
        # Load the image file into memory
        image = Image.open(uploaded_file)

        # Display the image
        st.image(image)

        # Extract the metadata
        metadata = image.tag_v2

        # Display the metadata
        st.write(metadata)
